# Generated by Django 3.1.7 on 2021-03-08 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Surname', models.CharField(max_length=64, null=True)),
                ('Birthday', models.DateField()),
                ('Email', models.EmailField(max_length=256)),
                ('Password', models.CharField(max_length=32)),
                ('PhoneNumber', models.CharField(max_length=16)),
                ('Address', models.CharField(max_length=128)),
                ('RegistrationDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(max_length=512)),
                ('Answer', models.TextField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Logo', models.ImageField(upload_to='')),
                ('Url', models.URLField()),
                ('Description', models.TextField(max_length=256)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=32)),
                ('City', models.CharField(max_length=32)),
                ('Address', models.CharField(max_length=128)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Partner', models.ManyToManyField(to='deliveryapp.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.URLField()),
                ('Color', models.CharField(max_length=32)),
                ('Size', models.CharField(max_length=16)),
                ('Amount', models.IntegerField()),
                ('OtherInfo', models.TextField(max_length=256)),
                ('Status', models.CharField(choices=[('PR', 'In Progress'), ('OR', 'Ordered'), ('DL', 'Delivered'), ('FN', 'Finished')], default='PR', max_length=2)),
                ('OrderDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryapp.customer')),
            ],
        ),
    ]
