# Generated by Django 3.1.7 on 2021-03-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='PhoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='RegistrationDate',
            new_name='registration_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Surname',
            new_name='surname',
        ),
    ]
